disabled = false
languageCode = "fr"
languageName = "Fran√ßais"
weight = 1
title = "Samuel Bond"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  description = ""

 [params.author]
   name = "Samuel Bond"
   email = "contact@samuelbond.dev"
   headline = "Bienvenue sur mon portfolio! :tada:"
   links = [
     { email = "mailto:contact@samuelbond.dev" },
     { github = "https://github.com/SamGamee" },
     { linkedin = "https://www.linkedin.com/in/samuel-bond-pro/" },
   ]
