name = "samuelbond-portfolio"
compatibility_date = "2026-02-13"
workers_dev = false
preview_urls = false

[build]
command = "./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"